Fix `IndexError`
At this moment, `get_distro_aliases()` tracebacks with:

```
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    get_distro_aliases()
    ~~~~~~~~~~~~~~~~~~^^
  File "src/opensuse_distro_aliases/__init__.py", line 70, in get_distro_aliases
    d = distro_list[0]
        ~~~~~~~~~~~^^^
IndexError: list index out of range
```

because the value for "Tumbleweed" in `distributions.json` is an empty list.

Handle such case.

Signed-off-by: Nikola Forró <nforro@redhat.com>